'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { foodIdentityLabel } from '@/lib/food/score-taste.ts';
import { rankFor } from '@/lib/match/score.ts';
import { seedProfiles, type SeedProfile } from '@/lib/match/seed-profiles.ts';
import type { MatchProfile, ScoredMatch } from '@/lib/match/types.ts';
import {
  coreProgress,
  nextQuestion,
  scorePsych,
  type PsychQuestion,
} from '@/lib/psych/psych-bank.ts';
import {
  clearPrefs,
  savePrefs,
  savePsychAnswer,
  useHydrated,
  useStoredPrefs,
  useStoredPsych,
  useStoredQuiz,
  type StoredPrefs,
} from '@/lib/quiz-storage.ts';
import { CITIES } from '@/lib/cities.ts';

/**
 * Explore, running against seeded profiles.
 *
 * Ranking happens on the client because the viewer's taste vector lives in
 * localStorage — there is no account yet. When onboarding lands this moves to
 * the server and reads from the database; `rankFor` does not change.
 */

type Verdict = 'like' | 'pass';

const GENDER_OPTIONS = [
  { id: 'woman', label: 'Woman' },
  { id: 'man', label: 'Man' },
  { id: 'non-binary', label: 'Non-binary' },
];

export default function ExploreFeed() {
  // These live in localStorage, which does not exist on the server. Subscribing
  // to them as an external store keeps the server and the first client paint in
  // agreement, and means a write anywhere (including another tab) re-renders
  // this component without any state to keep in sync by hand.
  const hydrated = useHydrated();
  const quiz = useStoredQuiz();
  const prefs = useStoredPrefs();
  const psych = useStoredPsych();
  const [verdicts, setVerdicts] = useState<Record<string, Verdict>>({});
  const [drip, setDrip] = useState<PsychQuestion | null>(null);

  const pool = useMemo(() => seedProfiles(64), []);

  const me: MatchProfile | null = useMemo(() => {
    if (!quiz || !prefs) return null;
    return {
      id: 'me',
      age: 28,
      gender: prefs.gender,
      seeking: prefs.seeking,
      ageMin: 21,
      ageMax: 45,
      city: 'bangalore',
      intents: ['exploring'],
      openToDistance: true,
      taste: quiz.vector,
      representativeDish: quiz.dishName,
      // Real answers when there are any. Unanswered traits are skipped by the
      // scorer rather than treated as agreement, so a thin Section 3 weakens the
      // psychological half honestly instead of inflating it.
      psych: scorePsych(psych),
      nonNegotiables: [],
      attributes: [],
    };
    // Every value the body reads belongs here. Listing only `quiz` once meant
    // submitting the gate updated `prefs` without recomputing `me`, and the
    // guard below sent the user back to the gate as if the button did nothing.
  }, [quiz, prefs, psych]);

  const ranked = useMemo(() => (me ? rankFor(me, pool) : null), [me, pool]);

  if (!hydrated) {
    return <p className="foot">Loading…</p>;
  }

  if (!quiz) {
    return (
      <>
        <h1>Take the quiz first</h1>
        <p className="lede">
          Explore ranks people against your food identity, so there is nothing to rank until you
          have one. It takes about ninety seconds.
        </p>
        <div className="spacer" />
        <Link href="/quiz" className="btn" style={{ textDecoration: 'none' }}>
          Find your food identity
        </Link>
      </>
    );
  }

  if (!prefs || !me || !ranked) {
    return <PrefsGate onDone={savePrefs} />;
  }

  const matches = ranked.matches;
  // Remaining, not indexed. Answering a drip question re-ranks the feed, and an
  // index would then silently point at a different person mid-swipe.
  const remaining = matches.filter((m) => !(m.profile.id in verdicts)) as Array<
    ScoredMatch & { profile: SeedProfile }
  >;
  const current = remaining[0];
  const decided = Object.keys(verdicts).length;
  const answeredIds = psych.map((a) => a.questionId);
  const progress = coreProgress(answeredIds);

  const decide = (verdict: Verdict) => {
    if (!current) return;
    setVerdicts((v) => ({ ...v, [current.profile.id]: verdict }));
    // Every fourth card, ask one question — the brief's "prompts shown while
    // swiping". Frequent enough to build a profile, rare enough not to feel
    // like a form.
    if ((decided + 1) % 4 === 0) {
      setDrip(nextQuestion(answeredIds));
    }
  };

  const liked = Object.values(verdicts).filter((v) => v === 'like').length;

  return (
    <>
      <div className="demo-banner" role="note">
        <strong>Demo profiles.</strong> Nobody below is a real person — they are generated by
        running the real quiz and the real scorer, so the feed behaves exactly as it will with
        actual users.
      </div>

      {!current ? (
        <div className="empty">
          <div className="empty-art" aria-hidden>🍽️</div>
          <h2>That is everyone for now</h2>
          <p>
            You liked {liked} of {matches.length}. In the real thing this is where you would wait
            for the pool to grow — which is exactly why the launch is one city at a time.
          </p>
          <button className="btn btn-ghost" onClick={() => { setVerdicts({}); setDrip(null); }}>
            Start over
          </button>
        </div>
      ) : (
        <>
          <div className="feed-head">
            <span className="feed-count">{decided + 1} of {matches.length}</span>
            <button
              className="feed-mine"
              onClick={() => { clearPrefs(); setVerdicts({}); setDrip(null); }}
            >
              {quiz.label} · change who you see
            </button>
          </div>

          {drip ? (
            <div className="drip">
              <p className="drip-label">One quick question</p>
              <h2>{drip.prompt}</h2>
              {drip.options.map((o) => (
                <button
                  key={o.id}
                  className="option"
                  onClick={() => {
                    savePsychAnswer({ questionId: drip.id, optionId: o.id });
                    setDrip(null);
                  }}
                >
                  <span className="option-title" style={{ fontWeight: 500 }}>{o.label}</span>
                </button>
              ))}
              <button
                className="btn-text"
                style={{ margin: '2px auto 0', display: 'block' }}
                onClick={() => setDrip(null)}
              >
                Skip
              </button>
            </div>
          ) : (
            <Card match={current} showScore={current.showScore} />
          )}

          {!drip && (
            <div className="verdicts">
              <button className="verdict pass" onClick={() => decide('pass')} aria-label="Pass">
                Pass
              </button>
              <button className="verdict like" onClick={() => decide('like')} aria-label="Like">
                Like
              </button>
            </div>
          )}

          {!current.showScore && (
            <p className="foot">
              Percentages stay hidden until there are enough people nearby for a number to mean
              something. Order still reflects the score.
            </p>
          )}

          {progress.done === 0 ? (
            <p className="foot">
              Half of every score is psychological compatibility, and you have not answered those
              questions yet — so these are food and intent only.{' '}
              <Link href="/questions">Answer twelve</Link>
            </p>
          ) : progress.done < progress.total ? (
            <p className="foot">
              {progress.done} of {progress.total} personality questions answered.{' '}
              <Link href="/questions">Answer the rest</Link> to sharpen these.
            </p>
          ) : (
            <p className="foot">All twelve answered — these scores use everything we have.</p>
          )}
        </>
      )}
    </>
  );
}

/**
 * Asks the two things the scorer will not guess.
 *
 * Real onboarding collects these. The demo has to as well, because the gender
 * gate fails closed: without them nobody matches, and the alternative — treating
 * silence as "show me everyone" — is what put women in a woman's feed.
 */
function PrefsGate({ onDone }: { onDone: (p: StoredPrefs) => void }) {
  const [gender, setGender] = useState('');
  const [seeking, setSeeking] = useState<string[]>([]);

  const toggle = (id: string) =>
    setSeeking((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));

  return (
    <>
      <h1>Two quick things</h1>
      <p className="lede">
        Explore only shows people where you both want to see each other, so we need this before
        anything else.
      </p>

      <p className="step-label" style={{ marginTop: 22 }}>I am</p>
      <div className="tiles">
        {GENDER_OPTIONS.map((g) => (
          <button
            key={g.id}
            className="tile"
            data-selected={gender === g.id}
            onClick={() => setGender(g.id)}
            aria-pressed={gender === g.id}
          >
            {g.label}
          </button>
        ))}
      </div>

      <p className="step-label">Show me</p>
      <div className="tiles">
        {GENDER_OPTIONS.map((g) => (
          <button
            key={g.id}
            className="tile"
            data-selected={seeking.includes(g.id)}
            onClick={() => toggle(g.id)}
            aria-pressed={seeking.includes(g.id)}
          >
            {g.label}
          </button>
        ))}
      </div>

      <div className="spacer" />
      <button
        className="btn"
        disabled={!gender || seeking.length === 0}
        onClick={() => onDone({ gender, seeking })}
      >
        See who you&apos;d match with
      </button>
    </>
  );
}

function Card({ match, showScore }: { match: ScoredMatch & { profile: SeedProfile }; showScore: boolean }) {
  const p = match.profile;
  const cityLabel = CITIES.find((c) => c.id === p.city)?.label ?? p.city;
  // The canonical label, so the card and the quiz result can never disagree.
  const identity = foodIdentityLabel(p.taste);

  return (
    <article className="card">
      {match.banner && (
        <div className="card-banner">
          We think you&apos;ll be a great match — you should try to meet.
        </div>
      )}

      <div className="card-photos">
        {/* Placeholder for the selfie-verified photo. */}
        <div className="card-portrait" aria-hidden>
          <span>{p.name.charAt(0)}</span>
        </div>
        <div className="card-dish" aria-hidden>
          <span>{p.dishEmoji}</span>
        </div>
      </div>

      <div className="card-body">
        <div className="card-top">
          <h2 className="card-name">
            {p.name}, {p.age}
          </h2>
          {showScore && (
            <span className={`card-score${match.displayScore >= 85 ? ' high' : ''}`}>
              {match.displayScore}%
            </span>
          )}
        </div>

        <p className="card-identity">{identity}</p>
        <p className="card-meta">
          {cityLabel}
          {p.representativeDish ? ` · ${p.representativeDish} person` : ''}
        </p>

        <p className="card-prompt">
          <span className="card-prompt-q">On my free days, I find myself</span>
          <br />
          {p.freeDays}
        </p>

        {match.chips.length > 0 ? (
          <div className="card-chips">
            {match.chips.map((c) => (
              <span key={c} className="chip">{c}</span>
            ))}
          </div>
        ) : (
          <p className="card-nothing">
            Nothing obvious in common yet. Answering the personality questions would give us
            something to go on.
          </p>
        )}
      </div>
    </article>
  );
}
