'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { foodIdentityLabel } from '@/lib/food/score-taste.ts';
import { rankFor } from '@/lib/match/score.ts';
import { seedProfiles, type SeedProfile } from '@/lib/match/seed-profiles.ts';
import type { MatchProfile, ScoredMatch } from '@/lib/match/types.ts';
import { scorePsych } from '@/lib/psych/psych-bank.ts';
import { loadPrefs, loadQuiz, savePrefs, type StoredPrefs } from '@/lib/quiz-storage.ts';
import { CITIES } from '@/lib/cities.ts';

/**
 * Explore, running against seeded profiles.
 *
 * Ranking happens on the client because the viewer's taste vector lives in
 * localStorage — there is no account yet. When onboarding lands this moves to
 * the server and reads from the database; `rankFor` does not change.
 */

type Verdict = 'like' | 'pass';

const GENDER_OPTIONS = [
  { id: 'woman', label: 'Woman' },
  { id: 'man', label: 'Man' },
  { id: 'non-binary', label: 'Non-binary' },
];

export default function ExploreFeed() {
  const quiz = useMemo(() => loadQuiz(), []);
  const [prefs, setPrefs] = useState<StoredPrefs | null>(null);
  const [prefsLoaded, setPrefsLoaded] = useState(false);
  const [index, setIndex] = useState(0);
  const [verdicts, setVerdicts] = useState<Record<string, Verdict>>({});

  // localStorage is client-only, so read it after mount rather than during
  // render — otherwise the server and the browser disagree on first paint.
  useEffect(() => {
    setPrefs(loadPrefs());
    setPrefsLoaded(true);
  }, []);

  const pool = useMemo(() => seedProfiles(30), []);

  const me: MatchProfile | null = useMemo(() => {
    if (!quiz || !prefs) return null;
    return {
      id: 'me',
      age: 28,
      gender: prefs.gender,
      seeking: prefs.seeking,
      ageMin: 21,
      ageMax: 45,
      city: 'bangalore',
      intents: ['exploring'],
      openToDistance: true,
      taste: quiz.vector,
      representativeDish: quiz.dishName,
      // Section 3 has not been asked yet, so the psychological half of every
      // score is genuinely neutral. The banner below says so rather than
      // letting the number imply more than we know.
      psych: scorePsych([]),
      nonNegotiables: [],
      attributes: [],
    };
  }, [quiz]);

  const ranked = useMemo(() => (me ? rankFor(me, pool) : null), [me, pool]);

  if (!quiz) {
    return (
      <>
        <h1>Take the quiz first</h1>
        <p className="lede">
          Explore ranks people against your food identity, so there is nothing to rank until you
          have one. It takes about ninety seconds.
        </p>
        <div className="spacer" />
        <Link href="/quiz" className="btn" style={{ textDecoration: 'none' }}>
          Find your food identity
        </Link>
      </>
    );
  }

  if (!prefsLoaded) return null;

  if (!prefs || !me || !ranked) {
    return <PrefsGate onDone={(p) => { savePrefs(p); setPrefs(p); }} />;
  }

  const matches = ranked.matches;
  const current = matches[index] as (ScoredMatch & { profile: SeedProfile }) | undefined;

  const decide = (verdict: Verdict) => {
    if (!current) return;
    setVerdicts((v) => ({ ...v, [current.profile.id]: verdict }));
    setIndex((i) => i + 1);
  };

  const liked = Object.values(verdicts).filter((v) => v === 'like').length;

  return (
    <>
      <div className="demo-banner" role="note">
        <strong>Demo profiles.</strong> Nobody below is a real person — they are generated by
        running the real quiz and the real scorer, so the feed behaves exactly as it will with
        actual users.
      </div>

      {!current ? (
        <div className="empty">
          <div className="empty-art" aria-hidden>🍽️</div>
          <h2>That is everyone for now</h2>
          <p>
            You liked {liked} of {matches.length}. In the real thing this is where you would wait
            for the pool to grow — which is exactly why the launch is one city at a time.
          </p>
          <button className="btn btn-ghost" onClick={() => { setIndex(0); setVerdicts({}); }}>
            Start over
          </button>
        </div>
      ) : (
        <>
          <div className="feed-head">
            <span className="feed-count">{index + 1} of {matches.length}</span>
            <button
              className="feed-mine"
              onClick={() => { setPrefs(null); setIndex(0); setVerdicts({}); }}
            >
              {quiz.label} · change who you see
            </button>
          </div>

          <Card match={current} showScore={current.showScore} />

          <div className="verdicts">
            <button className="verdict pass" onClick={() => decide('pass')} aria-label="Pass">
              Pass
            </button>
            <button className="verdict like" onClick={() => decide('like')} aria-label="Like">
              Like
            </button>
          </div>

          {!current.showScore && (
            <p className="foot">
              Percentages stay hidden until there are enough people nearby for a number to mean
              something. Order still reflects the score.
            </p>
          )}

          <p className="foot">
            Half of every score is psychological compatibility, and you have not answered those
            questions yet — so these are food and intent only.
          </p>
        </>
      )}
    </>
  );
}

/**
 * Asks the two things the scorer will not guess.
 *
 * Real onboarding collects these. The demo has to as well, because the gender
 * gate fails closed: without them nobody matches, and the alternative — treating
 * silence as "show me everyone" — is what put women in a woman's feed.
 */
function PrefsGate({ onDone }: { onDone: (p: StoredPrefs) => void }) {
  const [gender, setGender] = useState('');
  const [seeking, setSeeking] = useState<string[]>([]);

  const toggle = (id: string) =>
    setSeeking((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));

  return (
    <>
      <h1>Two quick things</h1>
      <p className="lede">
        Explore only shows people where you both want to see each other, so we need this before
        anything else.
      </p>

      <p className="step-label" style={{ marginTop: 22 }}>I am</p>
      <div className="tiles">
        {GENDER_OPTIONS.map((g) => (
          <button
            key={g.id}
            className="tile"
            data-selected={gender === g.id}
            onClick={() => setGender(g.id)}
            aria-pressed={gender === g.id}
          >
            {g.label}
          </button>
        ))}
      </div>

      <p className="step-label">Show me</p>
      <div className="tiles">
        {GENDER_OPTIONS.map((g) => (
          <button
            key={g.id}
            className="tile"
            data-selected={seeking.includes(g.id)}
            onClick={() => toggle(g.id)}
            aria-pressed={seeking.includes(g.id)}
          >
            {g.label}
          </button>
        ))}
      </div>

      <div className="spacer" />
      <button
        className="btn"
        disabled={!gender || seeking.length === 0}
        onClick={() => onDone({ gender, seeking })}
      >
        See who you&apos;d match with
      </button>
    </>
  );
}

function Card({ match, showScore }: { match: ScoredMatch & { profile: SeedProfile }; showScore: boolean }) {
  const p = match.profile;
  const cityLabel = CITIES.find((c) => c.id === p.city)?.label ?? p.city;
  // The canonical label, so the card and the quiz result can never disagree.
  const identity = foodIdentityLabel(p.taste);

  return (
    <article className="card">
      {match.banner && (
        <div className="card-banner">
          We think you&apos;ll be a great match — you should try to meet.
        </div>
      )}

      <div className="card-photos">
        {/* Placeholder for the selfie-verified photo. */}
        <div className="card-portrait" aria-hidden>
          <span>{p.name.charAt(0)}</span>
        </div>
        <div className="card-dish" aria-hidden>
          <span>{p.dishEmoji}</span>
        </div>
      </div>

      <div className="card-body">
        <div className="card-top">
          <h2 className="card-name">
            {p.name}, {p.age}
          </h2>
          {showScore && (
            <span className={`card-score${match.displayScore >= 85 ? ' high' : ''}`}>
              {match.displayScore}%
            </span>
          )}
        </div>

        <p className="card-identity">{identity}</p>
        <p className="card-meta">
          {cityLabel}
          {p.representativeDish ? ` · ${p.representativeDish} person` : ''}
        </p>

        <p className="card-prompt">
          <span className="card-prompt-q">On my free days, I find myself</span>
          <br />
          {p.freeDays}
        </p>

        {match.chips.length > 0 ? (
          <div className="card-chips">
            {match.chips.map((c) => (
              <span key={c} className="chip">{c}</span>
            ))}
          </div>
        ) : (
          <p className="card-nothing">
            Nothing obvious in common yet. Answering the personality questions would give us
            something to go on.
          </p>
        )}
      </div>
    </article>
  );
}
