import { getItem } from '../food/food-catalog.ts';
import { DEFAULT_ROUNDS, mulberry32, nextPair, representativeItem } from '../food/pair-generator.ts';
import { applyChoice, createAccumulator, finalise } from '../food/score-taste.ts';
import { FOOD_QUESTIONS, type FoodAnswer } from '../food/food-relationship.ts';
import {
  CONTINUOUS_AXES,
  DIET_BAND_ORDER,
  type ContinuousAxis,
  type Cuisine,
  type FoodItem,
} from '../food/types.ts';
import { PSYCH_BANK, scorePsych, type PsychAnswer } from '../psych/psych-bank.ts';
import type { Intent, MatchProfile } from './types.ts';

/**
 * Synthetic profiles for developing and tuning Explore.
 *
 * THESE ARE NOT PEOPLE. Every screen that renders them must say so — a dating
 * app that shows fabricated profiles without labelling them is running a con,
 * and the fact that this is a preview does not change what it looks like to
 * whoever opens the page.
 *
 * They are generated by actually running the quiz and the psych bank rather than
 * by writing plausible-looking numbers, so the feed exercises the real
 * estimator, the real calibration, and the real scorer. Tuning against
 * hand-written vectors would tell us how the card looks, not how it behaves.
 */

export interface SeedProfile extends MatchProfile {
  name: string;
  dishEmoji: string;
  /** The brief's "On my free days, I find myself ___" prompt. */
  freeDays: string;
}

const PEOPLE: Array<{ name: string; gender: string }> = [
  { name: 'Ananya', gender: 'woman' }, { name: 'Rohan', gender: 'man' },
  { name: 'Meera', gender: 'woman' }, { name: 'Arjun', gender: 'man' },
  { name: 'Kavya', gender: 'woman' }, { name: 'Ishaan', gender: 'man' },
  { name: 'Divya', gender: 'woman' }, { name: 'Karthik', gender: 'man' },
  { name: 'Sneha', gender: 'woman' }, { name: 'Aditya', gender: 'man' },
  { name: 'Riya', gender: 'woman' }, { name: 'Nikhil', gender: 'man' },
  { name: 'Tara', gender: 'woman' }, { name: 'Varun', gender: 'man' },
  { name: 'Priya', gender: 'woman' }, { name: 'Siddharth', gender: 'man' },
  { name: 'Nandini', gender: 'woman' }, { name: 'Rahul', gender: 'man' },
  { name: 'Aisha', gender: 'woman' }, { name: 'Dev', gender: 'man' },
  { name: 'Shruti', gender: 'woman' }, { name: 'Aman', gender: 'man' },
  { name: 'Lakshmi', gender: 'woman' }, { name: 'Vikram', gender: 'man' },
  { name: 'Pooja', gender: 'woman' }, { name: 'Rishi', gender: 'man' },
  { name: 'Anjali', gender: 'woman' }, { name: 'Gaurav', gender: 'man' },
  { name: 'Neha', gender: 'woman' }, { name: 'Sameer', gender: 'man' },
  { name: 'Ira', gender: 'woman' }, { name: 'Kabir', gender: 'man' },
  { name: 'Mitali', gender: 'woman' }, { name: 'Yash', gender: 'man' },
  { name: 'Sanjana', gender: 'woman' }, { name: 'Harsh', gender: 'man' },
  { name: 'Devika', gender: 'woman' }, { name: 'Manav', gender: 'man' },
  { name: 'Rhea', gender: 'woman' }, { name: 'Tanmay', gender: 'man' },
  { name: 'Aarti', gender: 'woman' }, { name: 'Kunal', gender: 'man' },
  { name: 'Simran', gender: 'woman' }, { name: 'Ravi', gender: 'man' },
  { name: 'Bhavna', gender: 'woman' }, { name: 'Omkar', gender: 'man' },
  { name: 'Charu', gender: 'woman' }, { name: 'Faisal', gender: 'man' },
  { name: 'Juhi', gender: 'woman' }, { name: 'Nitin', gender: 'man' },
  { name: 'Radhika', gender: 'woman' }, { name: 'Sahil', gender: 'man' },
  { name: 'Trisha', gender: 'woman' }, { name: 'Ujjwal', gender: 'man' },
  { name: 'Vidya', gender: 'woman' }, { name: 'Zain', gender: 'man' },
  { name: 'Ayesha', gender: 'woman' }, { name: 'Parth', gender: 'man' },
  { name: 'Malini', gender: 'woman' }, { name: 'Girish', gender: 'man' },
  { name: 'Sarita', gender: 'woman' }, { name: 'Imran', gender: 'man' },
];

const FREE_DAYS = [
  'walking the same three streets until something looks new',
  'in a bookshop I cannot afford to leave',
  'cooking for eight people who did not ask',
  'on a bike out past the ring road',
  'watching films nobody recommends',
  'at the same darshini, same order, since 2019',
  'losing at badminton, cheerfully',
  'reorganising a shelf that did not need it',
  'somewhere with bad signal on purpose',
  'arguing about music with people I like',
  'gardening badly on a small balcony',
  'chasing a dosa I had once in Madurai',
];

const CUISINES: Cuisine[] = [
  'north_indian', 'south_indian', 'bengali_east', 'west_indian',
  'mughlai', 'indo_chinese', 'continental', 'pan_asian', 'street',
];

const CITIES = ['bangalore', 'bangalore', 'bangalore', 'delhi', 'mumbai'];

export const GENDERS = ['woman', 'man', 'non-binary'] as const;

/**
 * Who a seeded person wants to see.
 *
 * The scorer requires this on BOTH sides, so leaving it empty would block the
 * entire pool. Distribution is mostly-but-not-only different-gender, and some
 * seeds include non-binary, so a viewer of any gender has someone to match with
 * and the mutual check is genuinely exercised rather than trivially true.
 */
function seekingFor(gender: string, rng: () => number): string[] {
  const roll = rng();
  const opposite = gender === 'woman' ? 'man' : 'woman';
  // Weighted so every viewer configuration has someone to see. At a realistic
  // same-gender share a pool of thirty leaves a lesbian viewer staring at an
  // empty feed, which reads as a broken demo rather than as thin data.
  if (roll < 0.6) return [opposite];
  if (roll < 0.8) return [gender];
  if (roll < 0.9) return [opposite, 'non-binary'];
  return ['woman', 'man', 'non-binary'];
}

/** Runs the real quiz for a simulated palate. */
function runQuizFor(rng: () => number) {
  const band = DIET_BAND_ORDER[Math.floor(rng() * DIET_BAND_ORDER.length)];
  const declared = [CUISINES[Math.floor(rng() * CUISINES.length)]];
  const ideal = {
    spice: rng(), richness: rng(), novelty: rng(), sweetness: rng() * 0.7,
  } as Record<ContinuousAxis, number>;

  const acc = createAccumulator(band, declared);
  const util = (it: FoodItem) =>
    CONTINUOUS_AXES.reduce((s, a) => s - (it[a] - ideal[a]) ** 2, 0) +
    (it.cuisine === declared[0] ? 0.35 : 0);

  for (let round = 1; round <= DEFAULT_ROUNDS; round++) {
    const pair = nextPair(acc, round, rng);
    if (!pair) break;
    const pa = 1 / (1 + Math.exp(-6 * (util(pair.left) - util(pair.right))));
    const winner = rng() < pa ? pair.left : pair.right;
    const loser = winner.id === pair.left.id ? pair.right : pair.left;
    applyChoice(
      acc,
      { round, winnerId: winner.id, loserId: loser.id, probing: pair.probing },
      winner,
      loser,
    );
  }
  return acc;
}

export function seedProfiles(count = 64, seed = 20260807): SeedProfile[] {
  const rng = mulberry32(seed);
  const out: SeedProfile[] = [];

  for (let i = 0; i < Math.min(count, PEOPLE.length); i++) {
    const person = PEOPLE[i];
    const acc = runQuizFor(rng);
    const rep = representativeItem(acc, getItem);

    const foodAnswers: FoodAnswer[] = FOOD_QUESTIONS.map((q) => ({
      questionId: q.id,
      optionId: q.options[Math.floor(rng() * q.options.length)].id,
    }));

    // Real answers to the real core questions, so the psych half of the score
    // is exercised rather than stubbed.
    const answers: PsychAnswer[] = PSYCH_BANK.filter((q) => q.tier === 'core').map((q) => ({
      questionId: q.id,
      optionId: q.options[Math.floor(rng() * q.options.length)].id,
    }));

    const intentRoll = rng();
    const intents: Intent[] =
      intentRoll < 0.55 ? ['long_term']
      : intentRoll < 0.75 ? ['long_term', 'marriage']
      : intentRoll < 0.9 ? ['casual', 'short_term']
      : ['exploring'];

    out.push({
      id: `seed-${i}`,
      name: person.name,
      gender: person.gender,
      age: 23 + Math.floor(rng() * 13),
      seeking: seekingFor(person.gender, rng),
      ageMin: 21,
      ageMax: 45,
      city: CITIES[Math.floor(rng() * CITIES.length)],
      intents,
      openToDistance: rng() < 0.5,
      taste: finalise(acc, foodAnswers),
      representativeDish: rep?.name,
      dishEmoji: rep?.emoji ?? '🍽️',
      psych: scorePsych(answers),
      nonNegotiables: [],
      attributes: [],
      freeDays: FREE_DAYS[Math.floor(rng() * FREE_DAYS.length)],
    });
  }

  return out;
}
