/**
 * Generates the constants in `pool-calibration.ts`.
 * Run: node --experimental-strip-types src/lib/food/calibrate-pool.ts
 *
 * WHY THIS EXISTS
 * ---------------
 * Each axis estimate is a weighted average of the values of dishes the user
 * chose, so its achievable range is set by what their diet band's pool contains
 * AND by how the adaptive probes move through it. That range is narrower and
 * differently placed than the raw spread of dish values — calibrating against
 * the menu instead of against the estimator saturated 47% of users at "Extra
 * Spicy" and clamped 78% of sweetness readings to an endpoint.
 *
 * So we measure it directly: simulate a large population of uniformly
 * distributed tastes through the real quiz, per band, and record the whole
 * quantile curve of the estimates that actually come out. The live scorer maps
 * through that curve, which makes the calibrated output uniform on 0..1 — so a
 * reading of 0.9 means "spicier than 90% of people in your diet band", and the
 * five card labels each land on a real share of the population.
 *
 * Two endpoints were not enough: a linear stretch preserves the shape of the
 * distribution, and that shape is U-shaped (adaptive probes force high-contrast
 * pairs, so the winners a user accumulates are rarely mid-range). That left 45%
 * of people labelled "Extra Spicy" and 33% "Mild", with the three middle bands
 * splitting the remaining fifth.
 *
 * There is no circularity here — pair selection reads RAW estimates, and
 * confidence does not depend on calibration, so the simulation is unaffected by
 * the constants it produces. Re-run this whenever the catalog changes.
 */
import { DEFAULT_ROUNDS, mulberry32, nextPair } from './pair-generator.ts';
import { applyChoice, createAccumulator, rawAxisEstimates } from './score-taste.ts';
import {
  CONTINUOUS_AXES,
  DIET_BAND_ORDER,
  type ContinuousAxis,
  type Cuisine,
  type DietBand,
  type FoodItem,
} from './types.ts';

const CUISINES: Cuisine[] = [
  'north_indian', 'south_indian', 'bengali_east', 'west_indian',
  'mughlai', 'indo_chinese', 'continental', 'pan_asian', 'street',
];

const SAMPLES_PER_BAND = 2000;
/** Knots of the emitted CDF, every 5th percentile from 0 to 1. */
const KNOTS = 21;

function quantile(sorted: number[], q: number): number {
  const pos = (sorted.length - 1) * q;
  const lo = Math.floor(pos);
  const hi = Math.ceil(pos);
  return sorted[lo] + (sorted[hi] - sorted[lo]) * (pos - lo);
}

function simulateBand(band: DietBand, seed: number): Record<ContinuousAxis, number[]> {
  const rng = mulberry32(seed);
  const out: Record<ContinuousAxis, number[]> = {
    spice: [], richness: [], novelty: [], sweetness: [],
  };

  for (let i = 0; i < SAMPLES_PER_BAND; i++) {
    const ideal: Record<ContinuousAxis, number> = {
      spice: rng(), richness: rng(), novelty: rng(),
      // Real users skew savoury; calibrating against a uniform sweet-tooth
      // population would make everyone read as a dessert person.
      sweetness: rng() * 0.7,
    };
    const fav = CUISINES[Math.floor(rng() * CUISINES.length)];
    const acc = createAccumulator(band, [fav]);
    const r = mulberry32(i * 977 + seed);
    const util = (it: FoodItem) =>
      CONTINUOUS_AXES.reduce((s, a) => s - (it[a] - ideal[a]) ** 2, 0) +
      (it.cuisine === fav ? 0.35 : 0);

    for (let round = 1; round <= DEFAULT_ROUNDS; round++) {
      const pair = nextPair(acc, round, r);
      if (!pair) break;
      const pa = 1 / (1 + Math.exp(-6 * (util(pair.left) - util(pair.right))));
      const winner = r() < pa ? pair.left : pair.right;
      const loser = winner.id === pair.left.id ? pair.right : pair.left;
      applyChoice(
        acc,
        { round, winnerId: winner.id, loserId: loser.id, probing: pair.probing },
        winner,
        loser,
      );
    }
    const raw = rawAxisEstimates(acc);
    for (const a of CONTINUOUS_AXES) out[a].push(raw[a]);
  }
  return out;
}

const lines: string[] = [];
lines.push('/** GENERATED by calibrate-pool.ts — do not edit by hand. */');
lines.push("import type { ContinuousAxis, DietBand } from './types.ts';");
lines.push('');
lines.push('/** Estimate value at each 5th percentile, per band and axis. */');
lines.push(
  'export const POOL_CALIBRATION: Record<DietBand, Record<ContinuousAxis, number[]>> = {',
);
for (const band of DIET_BAND_ORDER) {
  const sim = simulateBand(band, 20260805);
  lines.push(`  ${band}: {`);
  for (const axis of CONTINUOUS_AXES) {
    const sorted = sim[axis].sort((a, b) => a - b);
    const knots = Array.from({ length: KNOTS }, (_, k) =>
      quantile(sorted, k / (KNOTS - 1)).toFixed(4),
    );
    lines.push(`    ${axis}: [${knots.join(', ')}],`);
  }
  lines.push('  },');
}
lines.push('};');
lines.push('');

console.log(lines.join('\n'));
